### ISSUE TITLE
Annotation files

### ISSUE THREAD

**Issue by Mr-Pepe** [andreaskapou/Melissa-archive#1]
I might be constantly overlooking it in the paper and the documentation, but where did you get the annotation files from?

**Comment by andreaskapou** [comment]
I am a collaborator with the groups in Cambridge that developed scBS-seq (Smallwood, 2014, Nat Methods) and M&T-seq (Angermueller, 2016, Nat Methods), and I asked the authors to provide me with the original genomic annotations they used for their analyses. These are a collection of annotations from earlier studies, as mentioned in the above references, e.g. from https://www.pnas.org/content/107/50/21931. 

Hope this helps.

Best,
Andreas

**Comment by Mr-Pepe** [comment]
Yes, that helps!
Thank you very much for being so responsive.
